name: BMI Calculator CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Setup Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
    
      - name: List files in the calculate directory
        run: ls -la ./calculate
        

      # Step 2: Install dependencies
      - name: Install dependencies
        run: go get github.com/gin-gonic/gin
        working-directory: ./calculate  # Zapewniamy, że komenda działa w katalogu calculate

      # Step 3: Run go mod tidy
      - name: Go mod tidy
        run: go mod tidy
        working-directory: ./calculate  # Komenda go mod tidy działa w katalogu calculate

      # Step 4: Run tests
      - name: Run tests
        run: go test -v ./...
        working-directory: ./calculate  # Uruchomienie testów w katalogu calculate
