name: BMI Calculator CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Setup Go
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.23.1

            # Install dependencies
            - name: Install dependencies
              run: |
                cd calculate
                go get github.com/gin-gonic/gin
              working-directory: .

            # Run go mod tidy
            - name: Go mod tidy
              run: |
                cd calculate
                go mod tidy
              working-directory: .

            # Run tests
            - name: Run tests
              run: |
                cd calculate
                go test -v ./...
              working-directory: .
